
package testsFSG.defaul.features80;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.chocosolver.solver.ResolutionPolicy;
import org.chocosolver.solver.Solver;
import org.chocosolver.solver.constraints.Constraint;
import org.chocosolver.solver.constraints.IntConstraintFactory;
import org.chocosolver.solver.constraints.LogicalConstraintFactory;
import org.chocosolver.solver.constraints.SatFactory;
import org.chocosolver.solver.constraints.nary.cnf.LogOp;
import org.chocosolver.solver.search.loop.monitors.SMF;
import org.chocosolver.solver.search.strategy.IntStrategyFactory;
import org.chocosolver.solver.search.strategy.strategy.IntStrategy;
import org.chocosolver.solver.trace.Chatterbox;
import org.chocosolver.solver.variables.BoolVar;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.solver.variables.Variable;
import org.chocosolver.solver.variables.VariableFactory;
import searchStrategies.Utilities;

public class CoCoModelDefault2 {
	public static void main(String[] args) {
		Solver solver = new Solver();
		
		//--------------------------------------------
		//Features
		//--------------------------------------------
		int contFeatures = 80;
			
		BoolVar root1_root = (BoolVar) VariableFactory.fixed("feature_root1_root", 1, solver);
		BoolVar root1_F1 = VariableFactory.bool("feature_root1_F1", solver);
		BoolVar root1_F3 = VariableFactory.bool("feature_root1_F3", solver);
		BoolVar root1_F4 = VariableFactory.bool("feature_root1_F4", solver);
		BoolVar root1_F8 = VariableFactory.bool("feature_root1_F8", solver);
		BoolVar root1_F9 = VariableFactory.bool("feature_root1_F9", solver);
		BoolVar root1_F14 = VariableFactory.bool("feature_root1_F14", solver);
		BoolVar root1_F15 = VariableFactory.bool("feature_root1_F15", solver);
		BoolVar root1_F16 = VariableFactory.bool("feature_root1_F16", solver);
		BoolVar root1_F21 = VariableFactory.bool("feature_root1_F21", solver);
		BoolVar root1_F22 = VariableFactory.bool("feature_root1_F22", solver);
		BoolVar root1_F23 = VariableFactory.bool("feature_root1_F23", solver);
		BoolVar root1_F24 = VariableFactory.bool("feature_root1_F24", solver);
		BoolVar root1_F39 = VariableFactory.bool("feature_root1_F39", solver);
		BoolVar root1_F40 = VariableFactory.bool("feature_root1_F40", solver);
		BoolVar root1_F41 = VariableFactory.bool("feature_root1_F41", solver);
		BoolVar root1_F42 = VariableFactory.bool("feature_root1_F42", solver);
		BoolVar root1_F43 = VariableFactory.bool("feature_root1_F43", solver);
		BoolVar root1_F63 = VariableFactory.bool("feature_root1_F63", solver);
		BoolVar root1_F64 = VariableFactory.bool("feature_root1_F64", solver);
		BoolVar root1_F65 = VariableFactory.bool("feature_root1_F65", solver);
		BoolVar root1_F66 = VariableFactory.bool("feature_root1_F66", solver);
		BoolVar root1_F67 = VariableFactory.bool("feature_root1_F67", solver);
		BoolVar root1_F70 = VariableFactory.bool("feature_root1_F70", solver);
		BoolVar root1_F71 = VariableFactory.bool("feature_root1_F71", solver);
		BoolVar root1_F72 = VariableFactory.bool("feature_root1_F72", solver);
		BoolVar root1_F73 = VariableFactory.bool("feature_root1_F73", solver);
		BoolVar root1_F76 = VariableFactory.bool("feature_root1_F76", solver);
		BoolVar root1_F77 = VariableFactory.bool("feature_root1_F77", solver);
		BoolVar root1_F78 = VariableFactory.bool("feature_root1_F78", solver);
		BoolVar root1_F74 = VariableFactory.bool("feature_root1_F74", solver);
		BoolVar root1_F75 = VariableFactory.bool("feature_root1_F75", solver);
		BoolVar root1_F68 = VariableFactory.bool("feature_root1_F68", solver);
		BoolVar root1_F69 = VariableFactory.bool("feature_root1_F69", solver);
		BoolVar root1_F44 = VariableFactory.bool("feature_root1_F44", solver);
		BoolVar root1_F45 = VariableFactory.bool("feature_root1_F45", solver);
		BoolVar root1_F58 = VariableFactory.bool("feature_root1_F58", solver);
		BoolVar root1_F59 = VariableFactory.bool("feature_root1_F59", solver);
		BoolVar root1_F60 = VariableFactory.bool("feature_root1_F60", solver);
		BoolVar root1_F61 = VariableFactory.bool("feature_root1_F61", solver);
		BoolVar root1_F46 = VariableFactory.bool("feature_root1_F46", solver);
		BoolVar root1_F47 = VariableFactory.bool("feature_root1_F47", solver);
		BoolVar root1_F48 = VariableFactory.bool("feature_root1_F48", solver);
		BoolVar root1_F25 = VariableFactory.bool("feature_root1_F25", solver);
		BoolVar root1_F30 = VariableFactory.bool("feature_root1_F30", solver);
		BoolVar root1_F31 = VariableFactory.bool("feature_root1_F31", solver);
		BoolVar root1_F54 = VariableFactory.bool("feature_root1_F54", solver);
		BoolVar root1_F55 = VariableFactory.bool("feature_root1_F55", solver);
		BoolVar root1_F56 = VariableFactory.bool("feature_root1_F56", solver);
		BoolVar root1_F57 = VariableFactory.bool("feature_root1_F57", solver);
		BoolVar root1_F32 = VariableFactory.bool("feature_root1_F32", solver);
		BoolVar root1_F33 = VariableFactory.bool("feature_root1_F33", solver);
		BoolVar root1_F34 = VariableFactory.bool("feature_root1_F34", solver);
		BoolVar root1_F62 = VariableFactory.bool("feature_root1_F62", solver);
		BoolVar root1_F35 = VariableFactory.bool("feature_root1_F35", solver);
		BoolVar root1_F26 = VariableFactory.bool("feature_root1_F26", solver);
		BoolVar root1_F27 = VariableFactory.bool("feature_root1_F27", solver);
		BoolVar root1_F28 = VariableFactory.bool("feature_root1_F28", solver);
		BoolVar root1_F29 = VariableFactory.bool("feature_root1_F29", solver);
		BoolVar root1_F79 = VariableFactory.bool("feature_root1_F79", solver);
		BoolVar root1_F17 = VariableFactory.bool("feature_root1_F17", solver);
		BoolVar root1_F18 = VariableFactory.bool("feature_root1_F18", solver);
		BoolVar root1_F19 = VariableFactory.bool("feature_root1_F19", solver);
		BoolVar root1_F20 = VariableFactory.bool("feature_root1_F20", solver);
		BoolVar root1_F49 = VariableFactory.bool("feature_root1_F49", solver);
		BoolVar root1_F50 = VariableFactory.bool("feature_root1_F50", solver);
		BoolVar root1_F51 = VariableFactory.bool("feature_root1_F51", solver);
		BoolVar root1_F52 = VariableFactory.bool("feature_root1_F52", solver);
		BoolVar root1_F53 = VariableFactory.bool("feature_root1_F53", solver);
		BoolVar root1_F10 = VariableFactory.bool("feature_root1_F10", solver);
		BoolVar root1_F36 = VariableFactory.bool("feature_root1_F36", solver);
		BoolVar root1_F37 = VariableFactory.bool("feature_root1_F37", solver);
		BoolVar root1_F38 = VariableFactory.bool("feature_root1_F38", solver);
		BoolVar root1_F5 = VariableFactory.bool("feature_root1_F5", solver);
		BoolVar root1_F11 = VariableFactory.bool("feature_root1_F11", solver);
		BoolVar root1_F12 = VariableFactory.bool("feature_root1_F12", solver);
		BoolVar root1_F13 = VariableFactory.bool("feature_root1_F13", solver);
		BoolVar root1_F6 = VariableFactory.bool("feature_root1_F6", solver);
		BoolVar root1_F2 = VariableFactory.bool("feature_root1_F2", solver);
		BoolVar root1_F7 = VariableFactory.bool("feature_root1_F7", solver);
		
		//--------------------------------------------
		//Feature Attributes
		//--------------------------------------------
		HashMap<String, IntVar> featureAttrAtribute1 = new HashMap<String, IntVar>();
		HashMap<String, IntVar> featureAttrAtribute0 = new HashMap<String, IntVar>();
		
		featureAttrAtribute1.put("root1_F8", VariableFactory.enumerated("root1_F8Atribute1", new int[]{0, 76}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F8, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F8"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F8, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F8"), "!=", 0));
		featureAttrAtribute0.put("root1_F8", VariableFactory.enumerated("root1_F8Atribute0", new int[]{0, 66}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F8, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F8"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F8, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F8"), "!=", 0));
		featureAttrAtribute1.put("root1_F15", VariableFactory.enumerated("root1_F15Atribute1", new int[]{0, 57}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F15, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F15"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F15, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F15"), "!=", 0));
		featureAttrAtribute0.put("root1_F15", VariableFactory.enumerated("root1_F15Atribute0", new int[]{0, 1}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F15, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F15"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F15, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F15"), "!=", 0));
		featureAttrAtribute1.put("root1_F21", VariableFactory.enumerated("root1_F21Atribute1", new int[]{0, 12}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F21, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F21"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F21, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F21"), "!=", 0));
		featureAttrAtribute0.put("root1_F21", VariableFactory.enumerated("root1_F21Atribute0", new int[]{0, 93}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F21, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F21"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F21, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F21"), "!=", 0));
		featureAttrAtribute1.put("root1_F22", VariableFactory.enumerated("root1_F22Atribute1", new int[]{0, 30}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F22, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F22"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F22, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F22"), "!=", 0));
		featureAttrAtribute0.put("root1_F22", VariableFactory.enumerated("root1_F22Atribute0", new int[]{0, 23}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F22, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F22"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F22, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F22"), "!=", 0));
		featureAttrAtribute1.put("root1_F23", VariableFactory.enumerated("root1_F23Atribute1", new int[]{0, 40}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F23, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F23"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F23, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F23"), "!=", 0));
		featureAttrAtribute0.put("root1_F23", VariableFactory.enumerated("root1_F23Atribute0", new int[]{0, 50}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F23, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F23"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F23, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F23"), "!=", 0));
		featureAttrAtribute1.put("root1_F39", VariableFactory.enumerated("root1_F39Atribute1", new int[]{0, 58}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F39, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F39"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F39, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F39"), "!=", 0));
		featureAttrAtribute0.put("root1_F39", VariableFactory.enumerated("root1_F39Atribute0", new int[]{0, 11}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F39, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F39"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F39, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F39"), "!=", 0));
		featureAttrAtribute1.put("root1_F40", VariableFactory.enumerated("root1_F40Atribute1", new int[]{0, 88}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F40, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F40"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F40, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F40"), "!=", 0));
		featureAttrAtribute0.put("root1_F40", VariableFactory.enumerated("root1_F40Atribute0", new int[]{0, 88}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F40, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F40"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F40, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F40"), "!=", 0));
		featureAttrAtribute1.put("root1_F41", VariableFactory.enumerated("root1_F41Atribute1", new int[]{0, 77}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F41, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F41"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F41, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F41"), "!=", 0));
		featureAttrAtribute0.put("root1_F41", VariableFactory.enumerated("root1_F41Atribute0", new int[]{0, 30}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F41, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F41"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F41, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F41"), "!=", 0));
		featureAttrAtribute1.put("root1_F42", VariableFactory.enumerated("root1_F42Atribute1", new int[]{0, 14}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F42, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F42"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F42, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F42"), "!=", 0));
		featureAttrAtribute0.put("root1_F42", VariableFactory.enumerated("root1_F42Atribute0", new int[]{0, 61}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F42, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F42"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F42, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F42"), "!=", 0));
		featureAttrAtribute1.put("root1_F63", VariableFactory.enumerated("root1_F63Atribute1", new int[]{0, 74}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F63, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F63"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F63, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F63"), "!=", 0));
		featureAttrAtribute0.put("root1_F63", VariableFactory.enumerated("root1_F63Atribute0", new int[]{0, 100}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F63, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F63"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F63, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F63"), "!=", 0));
		featureAttrAtribute1.put("root1_F64", VariableFactory.enumerated("root1_F64Atribute1", new int[]{0, 52}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F64, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F64"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F64, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F64"), "!=", 0));
		featureAttrAtribute0.put("root1_F64", VariableFactory.enumerated("root1_F64Atribute0", new int[]{0, 16}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F64, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F64"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F64, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F64"), "!=", 0));
		featureAttrAtribute1.put("root1_F65", VariableFactory.enumerated("root1_F65Atribute1", new int[]{0, 87}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F65, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F65"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F65, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F65"), "!=", 0));
		featureAttrAtribute0.put("root1_F65", VariableFactory.enumerated("root1_F65Atribute0", new int[]{0, 21}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F65, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F65"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F65, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F65"), "!=", 0));
		featureAttrAtribute1.put("root1_F66", VariableFactory.enumerated("root1_F66Atribute1", new int[]{0, 93}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F66, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F66"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F66, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F66"), "!=", 0));
		featureAttrAtribute0.put("root1_F66", VariableFactory.enumerated("root1_F66Atribute0", new int[]{0, 24}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F66, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F66"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F66, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F66"), "!=", 0));
		featureAttrAtribute1.put("root1_F70", VariableFactory.enumerated("root1_F70Atribute1", new int[]{0, 71}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F70, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F70"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F70, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F70"), "!=", 0));
		featureAttrAtribute0.put("root1_F70", VariableFactory.enumerated("root1_F70Atribute0", new int[]{0, 52}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F70, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F70"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F70, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F70"), "!=", 0));
		featureAttrAtribute1.put("root1_F71", VariableFactory.enumerated("root1_F71Atribute1", new int[]{0, 78}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F71, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F71"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F71, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F71"), "!=", 0));
		featureAttrAtribute0.put("root1_F71", VariableFactory.enumerated("root1_F71Atribute0", new int[]{0, 25}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F71, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F71"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F71, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F71"), "!=", 0));
		featureAttrAtribute1.put("root1_F72", VariableFactory.enumerated("root1_F72Atribute1", new int[]{0, 6}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F72, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F72"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F72, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F72"), "!=", 0));
		featureAttrAtribute0.put("root1_F72", VariableFactory.enumerated("root1_F72Atribute0", new int[]{0, 52}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F72, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F72"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F72, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F72"), "!=", 0));
		featureAttrAtribute1.put("root1_F76", VariableFactory.enumerated("root1_F76Atribute1", new int[]{0, 43}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F76, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F76"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F76, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F76"), "!=", 0));
		featureAttrAtribute0.put("root1_F76", VariableFactory.enumerated("root1_F76Atribute0", new int[]{0, 3}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F76, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F76"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F76, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F76"), "!=", 0));
		featureAttrAtribute1.put("root1_F77", VariableFactory.enumerated("root1_F77Atribute1", new int[]{0, 89}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F77, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F77"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F77, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F77"), "!=", 0));
		featureAttrAtribute0.put("root1_F77", VariableFactory.enumerated("root1_F77Atribute0", new int[]{0, 13}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F77, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F77"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F77, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F77"), "!=", 0));
		featureAttrAtribute1.put("root1_F78", VariableFactory.enumerated("root1_F78Atribute1", new int[]{0, 26}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F78, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F78"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F78, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F78"), "!=", 0));
		featureAttrAtribute0.put("root1_F78", VariableFactory.enumerated("root1_F78Atribute0", new int[]{0, 43}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F78, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F78"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F78, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F78"), "!=", 0));
		featureAttrAtribute1.put("root1_F74", VariableFactory.enumerated("root1_F74Atribute1", new int[]{0, 100}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F74, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F74"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F74, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F74"), "!=", 0));
		featureAttrAtribute0.put("root1_F74", VariableFactory.enumerated("root1_F74Atribute0", new int[]{0, 56}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F74, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F74"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F74, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F74"), "!=", 0));
		featureAttrAtribute1.put("root1_F75", VariableFactory.enumerated("root1_F75Atribute1", new int[]{0, 10}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F75, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F75"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F75, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F75"), "!=", 0));
		featureAttrAtribute0.put("root1_F75", VariableFactory.enumerated("root1_F75Atribute0", new int[]{0, 53}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F75, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F75"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F75, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F75"), "!=", 0));
		featureAttrAtribute1.put("root1_F68", VariableFactory.enumerated("root1_F68Atribute1", new int[]{0, 70}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F68, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F68"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F68, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F68"), "!=", 0));
		featureAttrAtribute0.put("root1_F68", VariableFactory.enumerated("root1_F68Atribute0", new int[]{0, 32}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F68, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F68"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F68, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F68"), "!=", 0));
		featureAttrAtribute1.put("root1_F69", VariableFactory.enumerated("root1_F69Atribute1", new int[]{0, 16}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F69, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F69"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F69, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F69"), "!=", 0));
		featureAttrAtribute0.put("root1_F69", VariableFactory.enumerated("root1_F69Atribute0", new int[]{0, 15}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F69, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F69"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F69, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F69"), "!=", 0));
		featureAttrAtribute1.put("root1_F44", VariableFactory.enumerated("root1_F44Atribute1", new int[]{0, 67}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F44, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F44"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F44, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F44"), "!=", 0));
		featureAttrAtribute0.put("root1_F44", VariableFactory.enumerated("root1_F44Atribute0", new int[]{0, 57}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F44, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F44"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F44, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F44"), "!=", 0));
		featureAttrAtribute1.put("root1_F58", VariableFactory.enumerated("root1_F58Atribute1", new int[]{0, 88}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F58, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F58"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F58, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F58"), "!=", 0));
		featureAttrAtribute0.put("root1_F58", VariableFactory.enumerated("root1_F58Atribute0", new int[]{0, 16}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F58, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F58"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F58, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F58"), "!=", 0));
		featureAttrAtribute1.put("root1_F59", VariableFactory.enumerated("root1_F59Atribute1", new int[]{0, 42}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F59, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F59"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F59, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F59"), "!=", 0));
		featureAttrAtribute0.put("root1_F59", VariableFactory.enumerated("root1_F59Atribute0", new int[]{0, 43}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F59, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F59"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F59, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F59"), "!=", 0));
		featureAttrAtribute1.put("root1_F60", VariableFactory.enumerated("root1_F60Atribute1", new int[]{0, 28}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F60, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F60"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F60, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F60"), "!=", 0));
		featureAttrAtribute0.put("root1_F60", VariableFactory.enumerated("root1_F60Atribute0", new int[]{0, 51}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F60, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F60"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F60, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F60"), "!=", 0));
		featureAttrAtribute1.put("root1_F61", VariableFactory.enumerated("root1_F61Atribute1", new int[]{0, 61}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F61, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F61"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F61, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F61"), "!=", 0));
		featureAttrAtribute0.put("root1_F61", VariableFactory.enumerated("root1_F61Atribute0", new int[]{0, 42}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F61, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F61"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F61, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F61"), "!=", 0));
		featureAttrAtribute1.put("root1_F46", VariableFactory.enumerated("root1_F46Atribute1", new int[]{0, 52}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F46, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F46"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F46, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F46"), "!=", 0));
		featureAttrAtribute0.put("root1_F46", VariableFactory.enumerated("root1_F46Atribute0", new int[]{0, 24}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F46, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F46"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F46, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F46"), "!=", 0));
		featureAttrAtribute1.put("root1_F47", VariableFactory.enumerated("root1_F47Atribute1", new int[]{0, 14}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F47, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F47"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F47, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F47"), "!=", 0));
		featureAttrAtribute0.put("root1_F47", VariableFactory.enumerated("root1_F47Atribute0", new int[]{0, 95}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F47, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F47"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F47, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F47"), "!=", 0));
		featureAttrAtribute1.put("root1_F48", VariableFactory.enumerated("root1_F48Atribute1", new int[]{0, 98}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F48, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F48"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F48, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F48"), "!=", 0));
		featureAttrAtribute0.put("root1_F48", VariableFactory.enumerated("root1_F48Atribute0", new int[]{0, 83}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F48, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F48"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F48, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F48"), "!=", 0));
		featureAttrAtribute1.put("root1_F30", VariableFactory.enumerated("root1_F30Atribute1", new int[]{0, 58}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F30, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F30"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F30, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F30"), "!=", 0));
		featureAttrAtribute0.put("root1_F30", VariableFactory.enumerated("root1_F30Atribute0", new int[]{0, 92}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F30, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F30"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F30, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F30"), "!=", 0));
		featureAttrAtribute1.put("root1_F54", VariableFactory.enumerated("root1_F54Atribute1", new int[]{0, 35}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F54, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F54"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F54, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F54"), "!=", 0));
		featureAttrAtribute0.put("root1_F54", VariableFactory.enumerated("root1_F54Atribute0", new int[]{0, 7}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F54, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F54"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F54, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F54"), "!=", 0));
		featureAttrAtribute1.put("root1_F55", VariableFactory.enumerated("root1_F55Atribute1", new int[]{0, 18}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F55, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F55"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F55, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F55"), "!=", 0));
		featureAttrAtribute0.put("root1_F55", VariableFactory.enumerated("root1_F55Atribute0", new int[]{0, 84}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F55, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F55"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F55, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F55"), "!=", 0));
		featureAttrAtribute1.put("root1_F56", VariableFactory.enumerated("root1_F56Atribute1", new int[]{0, 47}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F56, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F56"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F56, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F56"), "!=", 0));
		featureAttrAtribute0.put("root1_F56", VariableFactory.enumerated("root1_F56Atribute0", new int[]{0, 26}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F56, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F56"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F56, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F56"), "!=", 0));
		featureAttrAtribute1.put("root1_F57", VariableFactory.enumerated("root1_F57Atribute1", new int[]{0, 60}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F57, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F57"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F57, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F57"), "!=", 0));
		featureAttrAtribute0.put("root1_F57", VariableFactory.enumerated("root1_F57Atribute0", new int[]{0, 57}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F57, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F57"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F57, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F57"), "!=", 0));
		featureAttrAtribute1.put("root1_F32", VariableFactory.enumerated("root1_F32Atribute1", new int[]{0, 30}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F32, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F32"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F32, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F32"), "!=", 0));
		featureAttrAtribute0.put("root1_F32", VariableFactory.enumerated("root1_F32Atribute0", new int[]{0, 11}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F32, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F32"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F32, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F32"), "!=", 0));
		featureAttrAtribute1.put("root1_F33", VariableFactory.enumerated("root1_F33Atribute1", new int[]{0, 13}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F33, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F33"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F33, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F33"), "!=", 0));
		featureAttrAtribute0.put("root1_F33", VariableFactory.enumerated("root1_F33Atribute0", new int[]{0, 64}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F33, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F33"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F33, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F33"), "!=", 0));
		featureAttrAtribute1.put("root1_F62", VariableFactory.enumerated("root1_F62Atribute1", new int[]{0, 68}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F62, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F62"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F62, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F62"), "!=", 0));
		featureAttrAtribute0.put("root1_F62", VariableFactory.enumerated("root1_F62Atribute0", new int[]{0, 66}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F62, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F62"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F62, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F62"), "!=", 0));
		featureAttrAtribute1.put("root1_F35", VariableFactory.enumerated("root1_F35Atribute1", new int[]{0, 17}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F35, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F35"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F35, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F35"), "!=", 0));
		featureAttrAtribute0.put("root1_F35", VariableFactory.enumerated("root1_F35Atribute0", new int[]{0, 50}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F35, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F35"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F35, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F35"), "!=", 0));
		featureAttrAtribute1.put("root1_F26", VariableFactory.enumerated("root1_F26Atribute1", new int[]{0, 2}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F26, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F26"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F26, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F26"), "!=", 0));
		featureAttrAtribute0.put("root1_F26", VariableFactory.enumerated("root1_F26Atribute0", new int[]{0, 79}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F26, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F26"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F26, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F26"), "!=", 0));
		featureAttrAtribute1.put("root1_F27", VariableFactory.enumerated("root1_F27Atribute1", new int[]{0, 39}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F27, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F27"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F27, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F27"), "!=", 0));
		featureAttrAtribute0.put("root1_F27", VariableFactory.enumerated("root1_F27Atribute0", new int[]{0, 27}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F27, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F27"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F27, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F27"), "!=", 0));
		featureAttrAtribute1.put("root1_F28", VariableFactory.enumerated("root1_F28Atribute1", new int[]{0, 63}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F28, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F28"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F28, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F28"), "!=", 0));
		featureAttrAtribute0.put("root1_F28", VariableFactory.enumerated("root1_F28Atribute0", new int[]{0, 46}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F28, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F28"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F28, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F28"), "!=", 0));
		featureAttrAtribute1.put("root1_F79", VariableFactory.enumerated("root1_F79Atribute1", new int[]{0, 4}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F79, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F79"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F79, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F79"), "!=", 0));
		featureAttrAtribute0.put("root1_F79", VariableFactory.enumerated("root1_F79Atribute0", new int[]{0, 70}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F79, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F79"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F79, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F79"), "!=", 0));
		featureAttrAtribute1.put("root1_F17", VariableFactory.enumerated("root1_F17Atribute1", new int[]{0, 71}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F17, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F17"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F17, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F17"), "!=", 0));
		featureAttrAtribute0.put("root1_F17", VariableFactory.enumerated("root1_F17Atribute0", new int[]{0, 51}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F17, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F17"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F17, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F17"), "!=", 0));
		featureAttrAtribute1.put("root1_F18", VariableFactory.enumerated("root1_F18Atribute1", new int[]{0, 78}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F18, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F18"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F18, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F18"), "!=", 0));
		featureAttrAtribute0.put("root1_F18", VariableFactory.enumerated("root1_F18Atribute0", new int[]{0, 74}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F18, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F18"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F18, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F18"), "!=", 0));
		featureAttrAtribute1.put("root1_F19", VariableFactory.enumerated("root1_F19Atribute1", new int[]{0, 98}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F19, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F19"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F19, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F19"), "!=", 0));
		featureAttrAtribute0.put("root1_F19", VariableFactory.enumerated("root1_F19Atribute0", new int[]{0, 9}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F19, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F19"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F19, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F19"), "!=", 0));
		featureAttrAtribute1.put("root1_F49", VariableFactory.enumerated("root1_F49Atribute1", new int[]{0, 7}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F49, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F49"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F49, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F49"), "!=", 0));
		featureAttrAtribute0.put("root1_F49", VariableFactory.enumerated("root1_F49Atribute0", new int[]{0, 82}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F49, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F49"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F49, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F49"), "!=", 0));
		featureAttrAtribute1.put("root1_F50", VariableFactory.enumerated("root1_F50Atribute1", new int[]{0, 100}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F50, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F50"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F50, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F50"), "!=", 0));
		featureAttrAtribute0.put("root1_F50", VariableFactory.enumerated("root1_F50Atribute0", new int[]{0, 83}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F50, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F50"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F50, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F50"), "!=", 0));
		featureAttrAtribute1.put("root1_F51", VariableFactory.enumerated("root1_F51Atribute1", new int[]{0, 78}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F51, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F51"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F51, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F51"), "!=", 0));
		featureAttrAtribute0.put("root1_F51", VariableFactory.enumerated("root1_F51Atribute0", new int[]{0, 27}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F51, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F51"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F51, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F51"), "!=", 0));
		featureAttrAtribute1.put("root1_F52", VariableFactory.enumerated("root1_F52Atribute1", new int[]{0, 28}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F52, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F52"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F52, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F52"), "!=", 0));
		featureAttrAtribute0.put("root1_F52", VariableFactory.enumerated("root1_F52Atribute0", new int[]{0, 12}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F52, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F52"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F52, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F52"), "!=", 0));
		featureAttrAtribute1.put("root1_F53", VariableFactory.enumerated("root1_F53Atribute1", new int[]{0, 77}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F53, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F53"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F53, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F53"), "!=", 0));
		featureAttrAtribute0.put("root1_F53", VariableFactory.enumerated("root1_F53Atribute0", new int[]{0, 35}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F53, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F53"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F53, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F53"), "!=", 0));
		featureAttrAtribute1.put("root1_F36", VariableFactory.enumerated("root1_F36Atribute1", new int[]{0, 79}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F36, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F36"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F36, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F36"), "!=", 0));
		featureAttrAtribute0.put("root1_F36", VariableFactory.enumerated("root1_F36Atribute0", new int[]{0, 89}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F36, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F36"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F36, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F36"), "!=", 0));
		featureAttrAtribute1.put("root1_F37", VariableFactory.enumerated("root1_F37Atribute1", new int[]{0, 23}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F37, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F37"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F37, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F37"), "!=", 0));
		featureAttrAtribute0.put("root1_F37", VariableFactory.enumerated("root1_F37Atribute0", new int[]{0, 62}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F37, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F37"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F37, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F37"), "!=", 0));
		featureAttrAtribute1.put("root1_F38", VariableFactory.enumerated("root1_F38Atribute1", new int[]{0, 91}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F38, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F38"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F38, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F38"), "!=", 0));
		featureAttrAtribute0.put("root1_F38", VariableFactory.enumerated("root1_F38Atribute0", new int[]{0, 43}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F38, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F38"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F38, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F38"), "!=", 0));
		featureAttrAtribute1.put("root1_F11", VariableFactory.enumerated("root1_F11Atribute1", new int[]{0, 72}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F11, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F11"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F11, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F11"), "!=", 0));
		featureAttrAtribute0.put("root1_F11", VariableFactory.enumerated("root1_F11Atribute0", new int[]{0, 73}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F11, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F11"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F11, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F11"), "!=", 0));
		featureAttrAtribute1.put("root1_F12", VariableFactory.enumerated("root1_F12Atribute1", new int[]{0, 15}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F12, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F12"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F12, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F12"), "!=", 0));
		featureAttrAtribute0.put("root1_F12", VariableFactory.enumerated("root1_F12Atribute0", new int[]{0, 60}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F12, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F12"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F12, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F12"), "!=", 0));
		featureAttrAtribute1.put("root1_F13", VariableFactory.enumerated("root1_F13Atribute1", new int[]{0, 71}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F13, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F13"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F13, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F13"), "!=", 0));
		featureAttrAtribute0.put("root1_F13", VariableFactory.enumerated("root1_F13Atribute0", new int[]{0, 43}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F13, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F13"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F13, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F13"), "!=", 0));
		featureAttrAtribute1.put("root1_F6", VariableFactory.enumerated("root1_F6Atribute1", new int[]{0, 97}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F6, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F6"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F6, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F6"), "!=", 0));
		featureAttrAtribute0.put("root1_F6", VariableFactory.enumerated("root1_F6Atribute0", new int[]{0, 80}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F6, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F6"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F6, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F6"), "!=", 0));
		featureAttrAtribute1.put("root1_F7", VariableFactory.enumerated("root1_F7Atribute1", new int[]{0, 99}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F7, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F7"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F7, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute1.get("root1_F7"), "!=", 0));
		featureAttrAtribute0.put("root1_F7", VariableFactory.enumerated("root1_F7Atribute0", new int[]{0, 80}, solver));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F7, "=", 0), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F7"), "=", 0));
		LogicalConstraintFactory.ifThen(IntConstraintFactory.arithm(root1_F7, "=", 1), IntConstraintFactory.arithm(featureAttrAtribute0.get("root1_F7"), "!=", 0));
		
		//--------------------------------------------
		//Tree Constraints
		//--------------------------------------------
		Constraint mandatoryroot1_root_root1_F1 = IntConstraintFactory.arithm(root1_root, "=", root1_F1);
		mandatoryroot1_root_root1_F1.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_root_root1_F1);
		Constraint mandatoryroot1_F1_root1_F3 = IntConstraintFactory.arithm(root1_F1, "=", root1_F3);
		mandatoryroot1_F1_root1_F3.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F1_root1_F3);
		Constraint optionalroot1_F3_root1_F4 = IntConstraintFactory.arithm(root1_F4, "<=", root1_F3);
		optionalroot1_F3_root1_F4.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F3_root1_F4);
		Constraint optionalroot1_F4_root1_F8 = IntConstraintFactory.arithm(root1_F8, "<=", root1_F4);
		optionalroot1_F4_root1_F8.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F4_root1_F8);
		IntVar sumOrroot1_F4_1 = VariableFactory.enumerated("sumOrroot1_F4", 0, 2, solver); 
		BoolVar[] varsOrroot1_F4_1 = new BoolVar[2];
		varsOrroot1_F4_1[0] = root1_F9;
		varsOrroot1_F4_1[1] = root1_F10;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F4_1, sumOrroot1_F4_1));
		Constraint or1root1_F4_1 = IntConstraintFactory.arithm(sumOrroot1_F4_1, ">=", 1);
		or1root1_F4_1.setName(Utilities.OR_TC);
		
		Constraint or0root1_F4_1 = IntConstraintFactory.arithm(sumOrroot1_F4_1, "=", 0);
		or0root1_F4_1.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F4, or1root1_F4_1, or0root1_F4_1);
			
		Constraint optionalroot1_F9_root1_F14 = IntConstraintFactory.arithm(root1_F14, "<=", root1_F9);
		optionalroot1_F9_root1_F14.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F9_root1_F14);
		Constraint optionalroot1_F14_root1_F15 = IntConstraintFactory.arithm(root1_F15, "<=", root1_F14);
		optionalroot1_F14_root1_F15.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F14_root1_F15);
		Constraint mandatoryroot1_F14_root1_F16 = IntConstraintFactory.arithm(root1_F14, "=", root1_F16);
		mandatoryroot1_F14_root1_F16.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F14_root1_F16);
		Constraint mandatoryroot1_F16_root1_F21 = IntConstraintFactory.arithm(root1_F16, "=", root1_F21);
		mandatoryroot1_F16_root1_F21.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F16_root1_F21);
		Constraint optionalroot1_F16_root1_F22 = IntConstraintFactory.arithm(root1_F22, "<=", root1_F16);
		optionalroot1_F16_root1_F22.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F16_root1_F22);
		Constraint mandatoryroot1_F16_root1_F23 = IntConstraintFactory.arithm(root1_F16, "=", root1_F23);
		mandatoryroot1_F16_root1_F23.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F16_root1_F23);
		Constraint mandatoryroot1_F16_root1_F24 = IntConstraintFactory.arithm(root1_F16, "=", root1_F24);
		mandatoryroot1_F16_root1_F24.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F16_root1_F24);
		Constraint optionalroot1_F24_root1_F39 = IntConstraintFactory.arithm(root1_F39, "<=", root1_F24);
		optionalroot1_F24_root1_F39.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F24_root1_F39);
		Constraint optionalroot1_F24_root1_F40 = IntConstraintFactory.arithm(root1_F40, "<=", root1_F24);
		optionalroot1_F24_root1_F40.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F24_root1_F40);
		Constraint optionalroot1_F24_root1_F41 = IntConstraintFactory.arithm(root1_F41, "<=", root1_F24);
		optionalroot1_F24_root1_F41.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F24_root1_F41);
		Constraint mandatoryroot1_F24_root1_F42 = IntConstraintFactory.arithm(root1_F24, "=", root1_F42);
		mandatoryroot1_F24_root1_F42.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F24_root1_F42);
		IntVar sumOrroot1_F24_4 = VariableFactory.enumerated("sumOrroot1_F24", 0, 3, solver); 
		BoolVar[] varsOrroot1_F24_4 = new BoolVar[3];
		varsOrroot1_F24_4[0] = root1_F43;
		varsOrroot1_F24_4[1] = root1_F44;
		varsOrroot1_F24_4[2] = root1_F45;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F24_4, sumOrroot1_F24_4));
		Constraint or1root1_F24_4 = IntConstraintFactory.arithm(sumOrroot1_F24_4, ">=", 1);
		or1root1_F24_4.setName(Utilities.OR_TC);
		
		Constraint or0root1_F24_4 = IntConstraintFactory.arithm(sumOrroot1_F24_4, "=", 0);
		or0root1_F24_4.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F24, or1root1_F24_4, or0root1_F24_4);
			
		Constraint mandatoryroot1_F43_root1_F63 = IntConstraintFactory.arithm(root1_F43, "=", root1_F63);
		mandatoryroot1_F43_root1_F63.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F43_root1_F63);
		Constraint optionalroot1_F43_root1_F64 = IntConstraintFactory.arithm(root1_F64, "<=", root1_F43);
		optionalroot1_F43_root1_F64.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F43_root1_F64);
		IntVar sumOrroot1_F43_2 = VariableFactory.enumerated("sumOrroot1_F43", 0, 2, solver); 
		BoolVar[] varsOrroot1_F43_2 = new BoolVar[2];
		varsOrroot1_F43_2[0] = root1_F65;
		varsOrroot1_F43_2[1] = root1_F66;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F43_2, sumOrroot1_F43_2));
		Constraint or1root1_F43_2 = IntConstraintFactory.arithm(sumOrroot1_F43_2, ">=", 1);
		or1root1_F43_2.setName(Utilities.OR_TC);
		
		Constraint or0root1_F43_2 = IntConstraintFactory.arithm(sumOrroot1_F43_2, "=", 0);
		or0root1_F43_2.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F43, or1root1_F43_2, or0root1_F43_2);
			
		Constraint mandatoryroot1_F43_root1_F67 = IntConstraintFactory.arithm(root1_F43, "=", root1_F67);
		mandatoryroot1_F43_root1_F67.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F43_root1_F67);
		Constraint optionalroot1_F67_root1_F70 = IntConstraintFactory.arithm(root1_F70, "<=", root1_F67);
		optionalroot1_F67_root1_F70.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F67_root1_F70);
		Constraint optionalroot1_F67_root1_F71 = IntConstraintFactory.arithm(root1_F71, "<=", root1_F67);
		optionalroot1_F67_root1_F71.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F67_root1_F71);
		IntVar sumOrroot1_F67_2 = VariableFactory.enumerated("sumOrroot1_F67", 0, 2, solver); 
		BoolVar[] varsOrroot1_F67_2 = new BoolVar[2];
		varsOrroot1_F67_2[0] = root1_F72;
		varsOrroot1_F67_2[1] = root1_F73;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F67_2, sumOrroot1_F67_2));
		Constraint or1root1_F67_2 = IntConstraintFactory.arithm(sumOrroot1_F67_2, ">=", 1);
		or1root1_F67_2.setName(Utilities.OR_TC);
		
		Constraint or0root1_F67_2 = IntConstraintFactory.arithm(sumOrroot1_F67_2, "=", 0);
		or0root1_F67_2.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F67, or1root1_F67_2, or0root1_F67_2);
			
		Constraint mandatoryroot1_F73_root1_F76 = IntConstraintFactory.arithm(root1_F73, "=", root1_F76);
		mandatoryroot1_F73_root1_F76.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F73_root1_F76);
		IntVar sumOrroot1_F73_1 = VariableFactory.enumerated("sumOrroot1_F73", 0, 2, solver); 
		BoolVar[] varsOrroot1_F73_1 = new BoolVar[2];
		varsOrroot1_F73_1[0] = root1_F77;
		varsOrroot1_F73_1[1] = root1_F78;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F73_1, sumOrroot1_F73_1));
		Constraint or1root1_F73_1 = IntConstraintFactory.arithm(sumOrroot1_F73_1, ">=", 1);
		or1root1_F73_1.setName(Utilities.OR_TC);
		
		Constraint or0root1_F73_1 = IntConstraintFactory.arithm(sumOrroot1_F73_1, "=", 0);
		or0root1_F73_1.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F73, or1root1_F73_1, or0root1_F73_1);
			
		Constraint mandatoryroot1_F67_root1_F74 = IntConstraintFactory.arithm(root1_F67, "=", root1_F74);
		mandatoryroot1_F67_root1_F74.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F67_root1_F74);
		Constraint mandatoryroot1_F67_root1_F75 = IntConstraintFactory.arithm(root1_F67, "=", root1_F75);
		mandatoryroot1_F67_root1_F75.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F67_root1_F75);
		Constraint mandatoryroot1_F43_root1_F68 = IntConstraintFactory.arithm(root1_F43, "=", root1_F68);
		mandatoryroot1_F43_root1_F68.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F43_root1_F68);
		Constraint mandatoryroot1_F43_root1_F69 = IntConstraintFactory.arithm(root1_F43, "=", root1_F69);
		mandatoryroot1_F43_root1_F69.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F43_root1_F69);
		Constraint optionalroot1_F45_root1_F58 = IntConstraintFactory.arithm(root1_F58, "<=", root1_F45);
		optionalroot1_F45_root1_F58.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F45_root1_F58);
		Constraint mandatoryroot1_F45_root1_F59 = IntConstraintFactory.arithm(root1_F45, "=", root1_F59);
		mandatoryroot1_F45_root1_F59.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F45_root1_F59);
		IntVar sumOrroot1_F45_2 = VariableFactory.enumerated("sumOrroot1_F45", 0, 2, solver); 
		BoolVar[] varsOrroot1_F45_2 = new BoolVar[2];
		varsOrroot1_F45_2[0] = root1_F60;
		varsOrroot1_F45_2[1] = root1_F61;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F45_2, sumOrroot1_F45_2));
		Constraint or1root1_F45_2 = IntConstraintFactory.arithm(sumOrroot1_F45_2, ">=", 1);
		or1root1_F45_2.setName(Utilities.OR_TC);
		
		Constraint or0root1_F45_2 = IntConstraintFactory.arithm(sumOrroot1_F45_2, "=", 0);
		or0root1_F45_2.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F45, or1root1_F45_2, or0root1_F45_2);
			
		Constraint mandatoryroot1_F24_root1_F46 = IntConstraintFactory.arithm(root1_F24, "=", root1_F46);
		mandatoryroot1_F24_root1_F46.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F24_root1_F46);
		Constraint mandatoryroot1_F24_root1_F47 = IntConstraintFactory.arithm(root1_F24, "=", root1_F47);
		mandatoryroot1_F24_root1_F47.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F24_root1_F47);
		Constraint mandatoryroot1_F24_root1_F48 = IntConstraintFactory.arithm(root1_F24, "=", root1_F48);
		mandatoryroot1_F24_root1_F48.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F24_root1_F48);
		Constraint mandatoryroot1_F16_root1_F25 = IntConstraintFactory.arithm(root1_F16, "=", root1_F25);
		mandatoryroot1_F16_root1_F25.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F16_root1_F25);
		Constraint optionalroot1_F25_root1_F30 = IntConstraintFactory.arithm(root1_F30, "<=", root1_F25);
		optionalroot1_F25_root1_F30.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F25_root1_F30);
		Constraint mandatoryroot1_F25_root1_F31 = IntConstraintFactory.arithm(root1_F25, "=", root1_F31);
		mandatoryroot1_F25_root1_F31.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F25_root1_F31);
		Constraint optionalroot1_F31_root1_F54 = IntConstraintFactory.arithm(root1_F54, "<=", root1_F31);
		optionalroot1_F31_root1_F54.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F31_root1_F54);
		Constraint mandatoryroot1_F31_root1_F55 = IntConstraintFactory.arithm(root1_F31, "=", root1_F55);
		mandatoryroot1_F31_root1_F55.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F31_root1_F55);
		Constraint mandatoryroot1_F31_root1_F56 = IntConstraintFactory.arithm(root1_F31, "=", root1_F56);
		mandatoryroot1_F31_root1_F56.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F31_root1_F56);
		Constraint mandatoryroot1_F31_root1_F57 = IntConstraintFactory.arithm(root1_F31, "=", root1_F57);
		mandatoryroot1_F31_root1_F57.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F31_root1_F57);
		IntVar sumOrroot1_F25_2 = VariableFactory.enumerated("sumOrroot1_F25", 0, 2, solver); 
		BoolVar[] varsOrroot1_F25_2 = new BoolVar[2];
		varsOrroot1_F25_2[0] = root1_F32;
		varsOrroot1_F25_2[1] = root1_F33;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F25_2, sumOrroot1_F25_2));
		Constraint or1root1_F25_2 = IntConstraintFactory.arithm(sumOrroot1_F25_2, ">=", 1);
		or1root1_F25_2.setName(Utilities.OR_TC);
		
		Constraint or0root1_F25_2 = IntConstraintFactory.arithm(sumOrroot1_F25_2, "=", 0);
		or0root1_F25_2.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F25, or1root1_F25_2, or0root1_F25_2);
			
		Constraint mandatoryroot1_F25_root1_F34 = IntConstraintFactory.arithm(root1_F25, "=", root1_F34);
		mandatoryroot1_F25_root1_F34.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F25_root1_F34);
		Constraint optionalroot1_F34_root1_F62 = IntConstraintFactory.arithm(root1_F62, "<=", root1_F34);
		optionalroot1_F34_root1_F62.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F34_root1_F62);
		Constraint mandatoryroot1_F25_root1_F35 = IntConstraintFactory.arithm(root1_F25, "=", root1_F35);
		mandatoryroot1_F25_root1_F35.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F25_root1_F35);
		Constraint mandatoryroot1_F16_root1_F26 = IntConstraintFactory.arithm(root1_F16, "=", root1_F26);
		mandatoryroot1_F16_root1_F26.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F16_root1_F26);
		Constraint mandatoryroot1_F16_root1_F27 = IntConstraintFactory.arithm(root1_F16, "=", root1_F27);
		mandatoryroot1_F16_root1_F27.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F16_root1_F27);
		Constraint mandatoryroot1_F16_root1_F28 = IntConstraintFactory.arithm(root1_F16, "=", root1_F28);
		mandatoryroot1_F16_root1_F28.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F16_root1_F28);
		Constraint mandatoryroot1_F16_root1_F29 = IntConstraintFactory.arithm(root1_F16, "=", root1_F29);
		mandatoryroot1_F16_root1_F29.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F16_root1_F29);
		Constraint mandatoryroot1_F29_root1_F79 = IntConstraintFactory.arithm(root1_F29, "=", root1_F79);
		mandatoryroot1_F29_root1_F79.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F29_root1_F79);
		IntVar sumOrroot1_F14_2 = VariableFactory.enumerated("sumOrroot1_F14", 0, 2, solver); 
		BoolVar[] varsOrroot1_F14_2 = new BoolVar[2];
		varsOrroot1_F14_2[0] = root1_F17;
		varsOrroot1_F14_2[1] = root1_F18;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F14_2, sumOrroot1_F14_2));
		Constraint or1root1_F14_2 = IntConstraintFactory.arithm(sumOrroot1_F14_2, ">=", 1);
		or1root1_F14_2.setName(Utilities.OR_TC);
		
		Constraint or0root1_F14_2 = IntConstraintFactory.arithm(sumOrroot1_F14_2, "=", 0);
		or0root1_F14_2.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F14, or1root1_F14_2, or0root1_F14_2);
			
		Constraint mandatoryroot1_F14_root1_F19 = IntConstraintFactory.arithm(root1_F14, "=", root1_F19);
		mandatoryroot1_F14_root1_F19.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F14_root1_F19);
		Constraint mandatoryroot1_F14_root1_F20 = IntConstraintFactory.arithm(root1_F14, "=", root1_F20);
		mandatoryroot1_F14_root1_F20.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F14_root1_F20);
		Constraint optionalroot1_F20_root1_F49 = IntConstraintFactory.arithm(root1_F49, "<=", root1_F20);
		optionalroot1_F20_root1_F49.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F20_root1_F49);
		Constraint mandatoryroot1_F20_root1_F50 = IntConstraintFactory.arithm(root1_F20, "=", root1_F50);
		mandatoryroot1_F20_root1_F50.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F20_root1_F50);
		Constraint mandatoryroot1_F20_root1_F51 = IntConstraintFactory.arithm(root1_F20, "=", root1_F51);
		mandatoryroot1_F20_root1_F51.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F20_root1_F51);
		IntVar sumOrroot1_F20_3 = VariableFactory.enumerated("sumOrroot1_F20", 0, 2, solver); 
		BoolVar[] varsOrroot1_F20_3 = new BoolVar[2];
		varsOrroot1_F20_3[0] = root1_F52;
		varsOrroot1_F20_3[1] = root1_F53;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F20_3, sumOrroot1_F20_3));
		Constraint or1root1_F20_3 = IntConstraintFactory.arithm(sumOrroot1_F20_3, ">=", 1);
		or1root1_F20_3.setName(Utilities.OR_TC);
		
		Constraint or0root1_F20_3 = IntConstraintFactory.arithm(sumOrroot1_F20_3, "=", 0);
		or0root1_F20_3.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F20, or1root1_F20_3, or0root1_F20_3);
			
		Constraint optionalroot1_F10_root1_F36 = IntConstraintFactory.arithm(root1_F36, "<=", root1_F10);
		optionalroot1_F10_root1_F36.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F10_root1_F36);
		Constraint optionalroot1_F10_root1_F37 = IntConstraintFactory.arithm(root1_F37, "<=", root1_F10);
		optionalroot1_F10_root1_F37.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F10_root1_F37);
		Constraint optionalroot1_F10_root1_F38 = IntConstraintFactory.arithm(root1_F38, "<=", root1_F10);
		optionalroot1_F10_root1_F38.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F10_root1_F38);
		IntVar sumOrroot1_F3_1 = VariableFactory.enumerated("sumOrroot1_F3", 0, 2, solver); 
		BoolVar[] varsOrroot1_F3_1 = new BoolVar[2];
		varsOrroot1_F3_1[0] = root1_F5;
		varsOrroot1_F3_1[1] = root1_F6;
		solver.post(IntConstraintFactory.sum(varsOrroot1_F3_1, sumOrroot1_F3_1));
		Constraint or1root1_F3_1 = IntConstraintFactory.arithm(sumOrroot1_F3_1, ">=", 1);
		or1root1_F3_1.setName(Utilities.OR_TC);
		
		Constraint or0root1_F3_1 = IntConstraintFactory.arithm(sumOrroot1_F3_1, "=", 0);
		or0root1_F3_1.setName(Utilities.OR_TC);
		LogicalConstraintFactory.ifThenElse(root1_F3, or1root1_F3_1, or0root1_F3_1);
			
		Constraint optionalroot1_F5_root1_F11 = IntConstraintFactory.arithm(root1_F11, "<=", root1_F5);
		optionalroot1_F5_root1_F11.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F5_root1_F11);
		Constraint mandatoryroot1_F5_root1_F12 = IntConstraintFactory.arithm(root1_F5, "=", root1_F12);
		mandatoryroot1_F5_root1_F12.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F5_root1_F12);
		Constraint optionalroot1_F5_root1_F13 = IntConstraintFactory.arithm(root1_F13, "<=", root1_F5);
		optionalroot1_F5_root1_F13.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_F5_root1_F13);
		Constraint optionalroot1_root_root1_F2 = IntConstraintFactory.arithm(root1_F2, "<=", root1_root);
		optionalroot1_root_root1_F2.setName(Utilities.OPTIONAL_TC);
		solver.post(optionalroot1_root_root1_F2);
		Constraint mandatoryroot1_F2_root1_F7 = IntConstraintFactory.arithm(root1_F2, "=", root1_F7);
		mandatoryroot1_F2_root1_F7.setName(Utilities.MANDATORY_TC);
		solver.post(mandatoryroot1_F2_root1_F7);
		
		//--------------------------------------------
		//Cross-Tree Constraints
		//--------------------------------------------
		Constraint requiresroot1_F2_root1_F35 = IntConstraintFactory.arithm(root1_F2, "<=", root1_F35);
		requiresroot1_F2_root1_F35.setName(Utilities.REQUIRES_CTC);
		solver.post(requiresroot1_F2_root1_F35);
		Constraint requiresroot1_F44_root1_F15 = IntConstraintFactory.arithm(root1_F44, "<=", root1_F15);
		requiresroot1_F44_root1_F15.setName(Utilities.REQUIRES_CTC);
		solver.post(requiresroot1_F44_root1_F15);
		Constraint requiresroot1_F36_root1_F35 = IntConstraintFactory.arithm(root1_F36, "<=", root1_F35);
		requiresroot1_F36_root1_F35.setName(Utilities.REQUIRES_CTC);
		solver.post(requiresroot1_F36_root1_F35);
		Constraint excludesroot1_F43_root1_F43 = IntConstraintFactory.arithm(root1_F43, "+", root1_F13, "<=", 1);
		excludesroot1_F43_root1_F43.setName(Utilities.EXCLUDES_CTC);
		solver.post(excludesroot1_F43_root1_F43);
		Constraint excludesroot1_F79_root1_F79 = IntConstraintFactory.arithm(root1_F79, "+", root1_F31, "<=", 1);
		excludesroot1_F79_root1_F79.setName(Utilities.EXCLUDES_CTC);
		solver.post(excludesroot1_F79_root1_F79);
		Constraint excludesroot1_F18_root1_F18 = IntConstraintFactory.arithm(root1_F18, "+", root1_F33, "<=", 1);
		excludesroot1_F18_root1_F18.setName(Utilities.EXCLUDES_CTC);
		solver.post(excludesroot1_F18_root1_F18);
		Constraint excludesroot1_F29_root1_F29 = IntConstraintFactory.arithm(root1_F29, "+", root1_F44, "<=", 1);
		excludesroot1_F29_root1_F29.setName(Utilities.EXCLUDES_CTC);
		solver.post(excludesroot1_F29_root1_F29);
		Constraint requiresroot1_F7_root1_F18 = IntConstraintFactory.arithm(root1_F7, "<=", root1_F18);
		requiresroot1_F7_root1_F18.setName(Utilities.REQUIRES_CTC);
		solver.post(requiresroot1_F7_root1_F18);
		
		//--------------------------------------------
		//Cross-Model Constraints
		//--------------------------------------------
		
		//--------------------------------------------
		//Solve
		//--------------------------------------------
		long start = System.currentTimeMillis();
		System.out.println("Started at: " + start);
		
		List<IntVar> varsAtribute0List = new ArrayList<IntVar>(featureAttrAtribute0.values());
		IntVar[] varsAtribute0 = new IntVar[featureAttrAtribute0.values().size()];
			
		for(int i = 0; i < varsAtribute0List.size(); i++) {
		varsAtribute0[i] = (IntVar) varsAtribute0List.get(i);
		}
		
		List<IntVar> varsAtribute1List = new ArrayList<IntVar>(featureAttrAtribute1.values());
		IntVar[] varsAtribute1 = new IntVar[featureAttrAtribute1.values().size()];
			
		for(int i = 0; i < varsAtribute1List.size(); i++) {
		varsAtribute1[i] = VariableFactory.minus(varsAtribute1List.get(i));
		}
		
		IntVar totalAtribute0 = VariableFactory.bounded("totalAtribute0", 0, 1000000, solver);
		solver.post(IntConstraintFactory.sum(varsAtribute0, totalAtribute0));
		IntVar totalAtribute1 = VariableFactory.bounded("totalAtribute1", -1000000, 0, solver);
		solver.post(IntConstraintFactory.sum(varsAtribute1, totalAtribute1));
		
		//SMF.limitSolution(solver, 10);
		//Chatterbox.showSolutions(solver);
		solver.findParetoFront(ResolutionPolicy.MINIMIZE, totalAtribute0, totalAtribute1);
		Chatterbox.printStatistics(solver);
		
		
		long end = System.currentTimeMillis();
		System.out.println("Ended at: " + end);
		System.out.println("Total time: " + (end - start));
	}
}